### ISSUE TITLE
[Feature Request] Добавить выгрузку в Excel для таблицы задач

### ISSUE THREAD

**Issue by RustaLenin** [anvarKhakimov/jira-metrics-plugin#7]
Было бы очень классно, если бы можно было содержимое таблицы по времени в статусе выгружать в Excel, чтобы далее там что-то с этим делать.

![image](https://github.com/anvarKhakimov/jira-metrics-plugin/assets/6325303/8c7db833-226a-47a1-be6b-5d357d542695)

**Comment by anvarKhakimov** [comment]
Выгрузка будет в формате CSV
